name: CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  test-build:
    runs-on: ubuntu-22.04
 
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Install dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
 
      # Build Project
      - name: Build Project
        run: npm run build
